---
documentclass: uncdissertation
classoption: report
linkcolor: black
fontsize: 11pt
output:
  pdf_document:
    includes:
      before_body: includes/tex/doc_prefix_unc.tex
      in_header: includes/tex/header-unc.tex
    keep_tex: no
    number_sections: yes
    toc: no
bibliography: includes/bib/bibliography.bib
csl: includes/bib/vancouver.csl
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

<!-- NOTE: All the .Rmd code here is based on work from https://github.com/jvcasill/ua_thesis_rmd. The original .cls file is from https://github.com/mmalahe/unc-dissertation  -->

<!-- % Include chapters -->

```{r, child='./sections/3_intro.Rmd'}
```

```{r, child='./sections/4_chapterX.Rmd'}
```

```{r, child='./sections/5_chapterY.Rmd'}
```

```{r, child='./sections/6_conclusion.Rmd'}
```


<!-- Include appendix -->

\appendix

```{r, child='./sections/appendices.Rmd'}
```


<!-- Include references -->

\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

\backmatter

\chapter*{References}
\bibliography{dissertation}
\addtocontents{toc}{\protect\vspace*{\baselineskip}}
<!-- \addcontentsline{toc}{chapter}{Bibliography} -->



<!-- \increferences{sections/references} -->